// Mocks generated by Mockito 5.4.6 from annotations
// in best_flutter/test/features/feed/domain/usecases/get_post_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:best_flutter/core/error/result.dart' as _i4;
import 'package:best_flutter/features/feed/domain/entities/post.dart' as _i5;
import 'package:best_flutter/features/feed/domain/repositories/feed_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FeedRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeedRepository extends _i1.Mock implements _i2.FeedRepository {
  MockFeedRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.Post>>> getPosts({
    required int? page,
    required int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPosts, [], {#page: page, #limit: limit}),
            returnValue: _i3.Future<_i4.Result<List<_i5.Post>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.Post>>>(
                this,
                Invocation.method(#getPosts, [], {#page: page, #limit: limit}),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Post>>>);

  @override
  _i3.Future<_i4.Result<_i5.Post>> createPost({
    required String? title,
    required String? body,
    required int? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPost, [], {
              #title: title,
              #body: body,
              #userId: userId,
            }),
            returnValue: _i3.Future<_i4.Result<_i5.Post>>.value(
              _i6.dummyValue<_i4.Result<_i5.Post>>(
                this,
                Invocation.method(#createPost, [], {
                  #title: title,
                  #body: body,
                  #userId: userId,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.Post>>);

  @override
  _i3.Future<_i4.Result<_i5.Post>> getPost(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPost, [id]),
            returnValue: _i3.Future<_i4.Result<_i5.Post>>.value(
              _i6.dummyValue<_i4.Result<_i5.Post>>(
                this,
                Invocation.method(#getPost, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.Post>>);

  @override
  _i3.Future<_i4.Result<_i5.Post>> updateLikes({
    required int? id,
    required int? likes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateLikes, [], {#id: id, #likes: likes}),
            returnValue: _i3.Future<_i4.Result<_i5.Post>>.value(
              _i6.dummyValue<_i4.Result<_i5.Post>>(
                this,
                Invocation.method(#updateLikes, [], {#id: id, #likes: likes}),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.Post>>);
}
